function vy_surfce_vis2(s_vol,vol_name, opt)

if opt.savenii == 1
    cfg = [];
    cfg.filetype  = 'nifti';
    cfg.datatype   = 'uint8'; %'float';
    cfg.parameter = 'anatomy';
    cfg.filename  = vol_name;
    ft_volumewrite(cfg, s_vol);
end

% For semi-inflation: state.selectedsurface=3; Full-inflation: state.selectedsurface=4;
conn_mesh_display(vol_name, '');
% title(['\fontsize{16} {\color{magenta}',[opt.tsk,', ',opt.subj,'-', opt.run],'}'],'interpreter','tex');
% pause(1.5);

savefig = [opt.savename,'.jpg'];
% conn_print(savefig,...
%     '-nogui',...
%     opt.view,...
%     get(findobj(gcf,'label','Left view'),'callback'),...
%     get(findobj(gcf,'label','Left medial view'),'callback'),...
%     get(findobj(gcf,'label','Right view'),'callback'),...
%     get(findobj(gcf,'label','Right medial view'),'callback'));

% savefig = [opt.savename,'.jpg'];
% conn_print(savefig,...
%     '-nogui',...
%     opt.view,...
%     get(findobj(gcf,'label','Inferior view'),'callback'));

if opt.savefig == 1
    savefig = [opt.savename,'.jpg'];
    
    switch opt.view
        case '-row'
            conn_print(savefig,...
                '-nogui',...
                opt.view,...
                get(findobj(gcf,'label','Left view'),'callback'),...
                get(findobj(gcf,'label','Right view'),'callback'),...
                get(findobj(gcf,'label','Superior view'),'callback'),...
                get(findobj(gcf,'label','Inferior view'),'callback'),...               
                get(findobj(gcf,'label','Right medial view'),'callback'),...
                get(findobj(gcf,'label','Left medial view'),'callback'));
            
        case  '-mosaic'
            conn_print(savefig,...
                '-nogui',...
                opt.view,...
                get(findobj(gcf,'label','Left view'),'callback'),...
                get(findobj(gcf,'label','Left medial view'),'callback'),...
                get(findobj(gcf,'label','Right view'),'callback'),...
                get(findobj(gcf,'label','Right medial view'),'callback'));
    end
end
end

% uimenu(hc1,'Label','Superior view','callback',{@conn_mesh_display_refresh,'view',[0,-.01,1],[],0},'tag','view');


%                 opt.view,...
%                 get(findobj(gcf,'label','Left view'),'callback'),...
%                 get(findobj(gcf,'label','Left medial view'),'callback'),...
%                 get(findobj(gcf,'label','Right view'),'callback'),...
%                 get(findobj(gcf,'label','Right medial view'),'callback'),...
%                 get(findobj(gcf,'label','Superior view'),'callback'),...
%                 get(findobj(gcf,'label','Inferior view'),'callback'));
